-- Reset map data with authentic JU 2025-26 reference map
DELETE FROM public.edges;
DELETE FROM public.nodes;

INSERT INTO public.nodes (id, name_bn, name_en, type, x, y, accessible) VALUES
  ('bishmail_gate', 'বিশমাইল গেট', 'Bishmail Gate', 'gate', 820, 60, true),
  ('prantik_gate', 'প্রান্তিক গেট', 'Prantik Gate', 'gate', 850, 320, true),
  ('main_gate', 'মেইন গেট', 'Main Gate', 'gate', 870, 1040, true),
  ('dairy_gate', 'ডেইরি গেট', 'Dairy Gate', 'gate', 880, 1080, true),
  ('mh_gate', 'এম এইচ হল গেট', 'M H Hall Gate', 'gate', 870, 1300, true),
  ('ju_school', 'জাবি স্কুল ও কলেজ', 'JU School & College', 'building', 640, 180, true),
  ('teacher_club', 'শিক্ষক ক্লাব', 'Teachers'' Club', 'building', 470, 360, true),
  ('public_health', 'পাবলিক হেলথ ভবন', 'Public Health Building', 'building', 290, 530, true),
  ('old_arts', 'পুরাতন কলা ভবন', 'Old Arts Building', 'building', 470, 530, true),
  ('business_fac', 'ব্যবসায় শিক্ষা অনুষদ', 'Business Studies Faculty', 'building', 420, 580, true),
  ('al_beruni', 'আল-বেরুনী হল', 'Al-Beruni Hall', 'building', 380, 625, true),
  ('medical_center', 'মেডিকেল সেন্টার', 'Medical Center', 'building', 450, 670, true),
  ('old_fazilatunnesa', 'পুরাতন ফজিলাতুন্নেসা হল', 'Old Fazilatunnesa Hall', 'building', 360, 740, true),
  ('fyzunnesa', 'ফয়জুন্নেসা হল', 'Fyzunnesa Hall', 'building', 770, 440, true),
  ('khaleda_zia', 'খালেদা জিয়া হল', 'Khaleda Zia Hall', 'building', 770, 525, true),
  ('july24', 'জুলাই ২৪ জাগরণী হল', 'July 24 Jagrani Hall', 'building', 770, 615, true),
  ('jahanara_imam', 'জাহানারা ইমাম হল', 'Jahanara Imam Hall', 'building', 600, 660, true),
  ('pritilata', 'প্রীতিলতা হল', 'Pritilata Hall', 'building', 600, 745, true),
  ('sufia_kamal', 'সুফিয়া কামাল হল', 'Sufia Kamal Hall', 'building', 740, 720, true),
  ('shahid_felani', 'শহীদ ফেলানী হল', 'Shahid Felani Hall', 'building', 800, 760, true),
  ('rokeya', 'রোকেয়া হল', 'Rokeya Hall', 'building', 830, 800, true),
  ('fazilatunnesa', 'ফজিলাতুন্নেসা হল', 'Fazilatunnesa Hall', 'building', 830, 840, true),
  ('taramon_bibi', 'তারামন বিবি হল', 'Taramon Bibi Hall', 'building', 830, 880, true),
  ('tarzan_point', 'টারজান পয়েন্ট', 'Tarzan Point', 'landmark', 740, 925, true),
  ('old_registrar', 'পুরাতন রেজিস্ট্রার ভবন', 'Old Registrar Building', 'building', 540, 770, true),
  ('math_stats', 'গণিত ও পরিসংখ্যান ভবন', 'Math & Stats Building', 'building', 620, 815, true),
  ('new_registrar', 'নতুন রেজিস্ট্রার ভবন', 'New Registrar Building', 'building', 460, 830, true),
  ('new_arts', 'নতুন কলা ভবন', 'New Arts Building', 'building', 530, 930, true),
  ('sociology_fac', 'সমাজবিজ্ঞান অনুষদ', 'Sociology Faculty', 'building', 660, 925, true),
  ('central_mosque', 'কেন্দ্রীয় মসজিদ', 'Central Mosque', 'landmark', 790, 960, true),
  ('mosque_center', 'মসজিদ', 'Campus Mosque', 'landmark', 290, 820, true),
  ('kola_bagan_mosque', 'কলাবাগান মসজিদ', 'Kola Bagan Mosque', 'landmark', 130, 780, true),
  ('shahid_tajuddin', 'শহীদ তাজউদ্দীন আহমদ হল', 'Shahid Tajuddin Ahmed Hall', 'building', 130, 840, true),
  ('shahid_salam', 'শহীদ সালাম-বরকত হল', 'Shahid Salam-Barkat Hall', 'building', 280, 835, true),
  ('nawab_salimullah', 'নবাব সলিমুল্লাহ হল', 'Nawab Salimullah Hall', 'building', 110, 895, true),
  ('kazi_nazrul', 'কাজী নজরুল ইসলাম হল', 'Kazi Nazrul Islam Hall', 'building', 240, 905, true),
  ('kamalapdin', 'কামালুদ্দিন হল', 'Kamaluddin Hall', 'building', 350, 920, true),
  ('maulana_bhashani', 'মওলানা ভাসানী হল', 'Maulana Bhashani Hall', 'building', 180, 975, true),
  ('shahid_rafiq', 'শহীদ রফিক-জব্বার হল', 'Shahid Rafiq-Jabbar Hall', 'building', 100, 1020, true),
  ('rabindranath', 'বিশ্বকবি রবীন্দ্রনাথ ঠাকুর হল', 'Rabindranath Tagore Hall', 'building', 80, 1100, true),
  ('sher_bangla', 'শেরে বাংলা হল', 'Sher-e-Bangla Hall', 'building', 260, 1100, true),
  ('mir_mosharraf', 'মীর মশাররফ হোসেন হল', 'Mir Mosharraf Hossain Hall', 'building', 640, 1300, true),
  ('central_library', 'সেন্ট্রাল লাইব্রেরি', 'Central Library', 'landmark', 430, 1010, true),
  ('shahid_minar', 'শহীদ মিনার', 'Shahid Minar', 'landmark', 520, 1035, true),
  ('auditorium', 'অডিটোরিয়াম (আইন বিভাগ)', 'Auditorium (Law Dept.)', 'building', 660, 1020, true),
  ('cafeteria', 'ক্যাফেটেরিয়া', 'Cafeteria', 'building', 720, 1075, true),
  ('physics', 'পদার্থবিজ্ঞান বিভাগ', 'Physics Department', 'building', 440, 1090, true),
  ('chemistry', 'রসায়ন বিভাগ', 'Chemistry Department', 'building', 540, 1130, true),
  ('geology_cse', 'ভূ-তত্ত্ব, সিএসই ও পরিবেশবিজ্ঞান ভবন', 'Geology, CSE & Environmental Sciences', 'building', 320, 1175, true),
  ('microbiology', 'মাইক্রোবায়োলজি ও বায়োটেকনোলজি', 'Microbiology & Biotechnology', 'building', 260, 1240, true),
  ('biological_sci', 'জীববিজ্ঞান অনুষদ', 'Biological Sciences Faculty', 'building', 310, 1295, true),
  ('wazed_mia', 'ওয়াজেদ মিয়া বিজ্ঞান গবেষণা কেন্দ্র', 'Wazed Mia Science Research Center', 'building', 460, 1240, true),
  ('comparative_lit', 'তুলনামূলক সাহিত্য ও সংস্কৃতি', 'Comparative Literature & Culture', 'building', 510, 1295, true),
  ('kendrio_mondir', 'কেন্দ্রীয় মন্দির', 'Central Temple', 'landmark', 720, 1230, true),
  ('botanical_garden', 'বোটানিক্যাল গার্ডেন', 'Botanical Garden', 'landmark', 490, 1360, true),
  ('ix_north', 'উত্তর সংযোগ', 'North Junction', 'intersection', 700, 280, true),
  ('ix_old_arts', 'কলা ভবন মোড়', 'Old Arts Junction', 'intersection', 540, 540, true),
  ('ix_mid', 'মধ্য মোড়', 'Central Junction', 'intersection', 540, 720, true),
  ('ix_mid_south', 'মধ্য-দক্ষিণ মোড়', 'Mid-South Junction', 'intersection', 540, 870, true),
  ('ix_library', 'লাইব্রেরি মোড়', 'Library Junction', 'intersection', 540, 1010, true),
  ('ix_south', 'দক্ষিণ মোড়', 'South Junction', 'intersection', 540, 1180, true),
  ('ix_east', 'পূর্ব মোড়', 'East Junction', 'intersection', 730, 1000, true);

INSERT INTO public.edges (from_node, to_node, distance, has_stairs, has_ramp, has_elevator, is_accessible, surface) VALUES
  ('bishmail_gate', 'ju_school', 216.33, false, true, false, true, 'paved'),
  ('ju_school', 'ix_north', 116.62, false, true, false, true, 'paved'),
  ('ix_north', 'prantik_gate', 155.24, false, true, false, true, 'paved'),
  ('ix_north', 'teacher_club', 243.52, false, true, false, true, 'paved'),
  ('teacher_club', 'old_arts', 170.0, false, true, false, true, 'paved'),
  ('teacher_club', 'public_health', 247.59, false, true, false, true, 'paved'),
  ('public_health', 'old_arts', 180.0, false, true, false, true, 'paved'),
  ('old_arts', 'ix_old_arts', 70.71, false, true, false, true, 'paved'),
  ('old_arts', 'business_fac', 70.71, false, true, false, true, 'paved'),
  ('business_fac', 'al_beruni', 60.21, false, true, false, true, 'paved'),
  ('al_beruni', 'medical_center', 83.22, false, true, false, true, 'paved'),
  ('medical_center', 'old_fazilatunnesa', 114.02, false, true, false, true, 'paved'),
  ('medical_center', 'ix_mid', 102.96, false, true, false, true, 'paved'),
  ('old_fazilatunnesa', 'mosque_center', 106.3, false, true, false, true, 'paved'),
  ('prantik_gate', 'fyzunnesa', 144.22, false, true, false, true, 'paved'),
  ('fyzunnesa', 'khaleda_zia', 85.0, false, true, false, true, 'paved'),
  ('khaleda_zia', 'july24', 90.0, false, true, false, true, 'paved'),
  ('july24', 'jahanara_imam', 175.86, false, true, false, true, 'paved'),
  ('july24', 'sufia_kamal', 109.2, false, true, false, true, 'paved'),
  ('jahanara_imam', 'pritilata', 85.0, false, true, false, true, 'paved'),
  ('sufia_kamal', 'shahid_felani', 72.11, false, true, false, true, 'paved'),
  ('shahid_felani', 'rokeya', 50.0, false, true, false, true, 'paved'),
  ('rokeya', 'fazilatunnesa', 40.0, false, true, false, true, 'paved'),
  ('fazilatunnesa', 'taramon_bibi', 40.0, false, true, false, true, 'paved'),
  ('taramon_bibi', 'tarzan_point', 100.62, false, true, false, true, 'paved'),
  ('pritilata', 'tarzan_point', 228.04, false, true, false, true, 'paved'),
  ('tarzan_point', 'central_mosque', 61.03, false, true, false, true, 'paved'),
  ('ix_old_arts', 'ix_mid', 180.0, false, true, false, true, 'paved'),
  ('ix_mid', 'old_registrar', 50.0, false, true, false, true, 'paved'),
  ('ix_mid', 'ix_mid_south', 150.0, false, true, false, true, 'paved'),
  ('old_registrar', 'math_stats', 92.2, false, true, false, true, 'paved'),
  ('old_registrar', 'new_registrar', 100.0, false, true, false, true, 'paved'),
  ('ix_mid_south', 'new_arts', 60.83, false, true, false, true, 'paved'),
  ('ix_mid_south', 'new_registrar', 89.22, false, true, false, true, 'paved'),
  ('ix_mid_south', 'sociology_fac', 130.86, false, true, false, true, 'paved'),
  ('sociology_fac', 'central_mosque', 137.93, false, true, false, true, 'paved'),
  ('sociology_fac', 'math_stats', 113.14, false, true, false, true, 'paved'),
  ('ix_mid_south', 'ix_library', 140.0, false, true, false, true, 'paved'),
  ('new_arts', 'central_library', 130.96, false, true, false, true, 'paved'),
  ('central_library', 'ix_library', 110.0, false, true, false, true, 'paved'),
  ('ix_library', 'shahid_minar', 31.4, false, true, false, true, 'paved'),
  ('ix_library', 'auditorium', 120.42, false, true, false, true, 'paved'),
  ('auditorium', 'ix_east', 70.71, false, true, false, true, 'paved'),
  ('ix_east', 'cafeteria', 75.66, false, true, false, true, 'paved'),
  ('ix_east', 'main_gate', 145.6, false, true, false, true, 'paved'),
  ('main_gate', 'dairy_gate', 41.23, false, true, false, true, 'paved'),
  ('central_mosque', 'auditorium', 144.91, false, true, false, true, 'paved'),
  ('cafeteria', 'kendrio_mondir', 155.0, false, true, false, true, 'paved'),
  ('mosque_center', 'kola_bagan_mosque', 164.92, false, true, false, true, 'paved'),
  ('mosque_center', 'shahid_salam', 18.03, false, true, false, true, 'paved'),
  ('kola_bagan_mosque', 'shahid_tajuddin', 60.0, false, true, false, true, 'paved'),
  ('shahid_tajuddin', 'nawab_salimullah', 56.79, false, true, false, true, 'paved'),
  ('shahid_salam', 'kazi_nazrul', 84.85, false, true, false, true, 'paved'),
  ('kazi_nazrul', 'kamalapdin', 110.91, false, true, false, true, 'paved'),
  ('kamalapdin', 'new_registrar', 137.85, false, true, false, true, 'paved'),
  ('nawab_salimullah', 'maulana_bhashani', 100.4, false, true, false, true, 'paved'),
  ('maulana_bhashani', 'shahid_rafiq', 90.14, false, true, false, true, 'paved'),
  ('shahid_rafiq', 'rabindranath', 82.46, false, true, false, true, 'paved'),
  ('maulana_bhashani', 'sher_bangla', 142.13, false, true, false, true, 'paved'),
  ('sher_bangla', 'central_library', 192.94, false, true, false, true, 'paved'),
  ('shahid_minar', 'physics', 91.92, false, true, false, true, 'paved'),
  ('shahid_minar', 'chemistry', 96.05, false, true, false, true, 'paved'),
  ('physics', 'chemistry', 105.83, false, true, false, true, 'paved'),
  ('physics', 'geology_cse', 144.91, false, true, false, true, 'paved'),
  ('chemistry', 'ix_south', 50.0, false, true, false, true, 'paved'),
  ('geology_cse', 'microbiology', 92.2, false, true, false, true, 'paved'),
  ('microbiology', 'biological_sci', 75.66, false, true, false, true, 'paved'),
  ('biological_sci', 'comparative_lit', 200.0, false, true, false, true, 'paved'),
  ('ix_south', 'wazed_mia', 100.8, false, true, false, true, 'paved'),
  ('wazed_mia', 'comparative_lit', 78.1, false, true, false, true, 'paved'),
  ('wazed_mia', 'kendrio_mondir', 260.0, false, true, false, true, 'paved'),
  ('kendrio_mondir', 'mh_gate', 165.53, false, true, false, true, 'paved'),
  ('comparative_lit', 'mir_mosharraf', 130.1, false, true, false, true, 'paved'),
  ('mir_mosharraf', 'mh_gate', 230.11, false, true, false, true, 'paved'),
  ('mir_mosharraf', 'botanical_garden', 169.93, false, true, false, true, 'paved'),
  ('comparative_lit', 'botanical_garden', 67.27, false, true, false, true, 'paved'),
  ('central_library', 'shahid_minar', 95.21, true, false, false, false, 'stairs'),
  ('auditorium', 'shahid_minar', 140.8, true, false, false, false, 'stairs'),
  ('sufia_kamal', 'rokeya', 120.42, true, false, false, false, 'stairs');